pipeline:

  # Integrate map detetcor data
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: map.yaml
            schema: MapConfig
        - common.YAMLReader:
            filename: integration.yaml
            schema: IntegrationConfig
  - common.IntegrateMapProcessor
  - common.NexusWriter:
      filename: map_reduceddata.nxs
      force_overwrite: true
