name: ChessPipeline
channels:
  - defaults
  - conda-forge
  - hexrd
  # - file://path/to/custom/msnctools/channel # path is on the CLASSE filesystem.
dependencies:
  - msnctools==2023.1.3
  - xarray==2023.2.0
  - nexusformat==0.7.8
  - pydantic==1.10.4
  - pyfai==2023.1.0
  - hexrd==0.8.19
  - xrayutilities==1.7.4