pipeline:
  - reader.Reader:
      filename: data.csv
  - processor.Processor: {}
  - processor.Processor: {}
  - writer.Writer:
      filename: data.out
  - processor.Processor: {}
  - writer.Writer:
      filename: data.out
