pipeline:

  # Download example data
  # gitlab API doesn't allow retrieval of files larger than 250MB, so skip at this point
#  - common.URLReader:
#      url: https://gitlab01.classe.cornell.edu/api/v4/projects/308/repository/files/sin2psi%2fdata.tar/raw?ref=main
#      headers:
#        PRIVATE-TOKEN: # your token here
#  - common.ExtractArchiveWriter:
#      filename: examples/sin2psi

  # Collect map data
  - common.YAMLReader:
      filename: examples/sin2psi/map.yaml
      schema: MapConfig
  - common.MapProcessor
  - common.NexusWriter:
      filename: examples/sin2psi/map.nxs
      force_overwrite: true

  # Integrate map detector data
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: examples/sin2psi/map.yaml
            schema: MapConfig
        - common.YAMLReader:
            filename: examples/sin2psi/integration.yaml
            schema: IntegrationConfig
  - common.IntegrateMapProcessor
  - common.NexusWriter:
      filename: examples/sin2psi/integrated_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: examples/sin2psi/integrated_detector_data.nxs
        - common.YAMLReader:
            filename: examples/sin2psi/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - common.StrainAnalysisProcessor
  - common.YAMLWriter:
      filename: examples/sin2psi/sample_strain_data.yaml
      force_overwrite: true

