pipeline:

  # Collect map data
  - common.YAMLReader:
      filename: examples/sin2psi/map.yaml
      schema: MapConfig
  - common.MapProcessor
  - common.NexusWriter:
      filename: examples/sin2psi/map.nxs
      force_overwrite: true

  # Integrate map detector data
  - common.MultipleReader:
      readers:
        - YAMLReader:
            filename: examples/sin2psi/map.yaml
            schema: MapConfig
        - YAMLReader:
            filename: examples/sin2psi/integration.yaml
            schema: IntegrationConfig
  - common.IntegrateMapProcessor
  - common.NexusWriter:
      filename: examples/sin2psi/integrated_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - common.MultipleReader:
      readers:
        - NexusReader:
            filename: examples/sin2psi/integrated_detector_data.nxs
        - YAMLReader:
            filename: examples/sin2psi/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - common.StrainAnalysisProcessor
  - common.YAMLWriter:
      filename: examples/sin2psi/sample_strain_data.yaml
      force_overwrite: true

