name: Deploy Sphinx documentation to Pages

#on:
#  push:
#    tags:
#    - v*.*.*
on:
  push:
    branches:
    - docs

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update docs configuration with version (tag) name
      run: |
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/conf.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/installation.md

    - name: Build and deploy docs
      id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
