pipeline:

  # Collect map data
  - reader.YAMLReader:
      filename: sin2psi_config/map.yaml
      schema: MapConfig
  - processor.MapProcessor
  - writer.NexusWriter:
      filename: sin2psi_data/map.nxs
      force_overwrite: true

  # Integrate map detector data
  - reader.MultipleReader:
      readers:
        - YAMLReader:
            filename: sin2psi_config/map.yaml
            schema: MapConfig
        - YAMLReader:
            filename: sin2psi_config/integration.yaml
            schema: IntegrationConfig
  - processor.IntegrationProcessor
  - writer.NexusWriter:
      filename: sin2psi_data/integrated_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - reader.MultipleReader:
      readers:
        - NexusReader:
            filename: sin2psi_data/integrated_detector_data.nxs
        - YAMLReader:
            filename: sin2psi_config/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - processor.StrainAnalysisProcessor
  - writer.YAMLWriter:
      filename: sin2psi_data/sample_strain_data.yaml
      force_overwrite: true

