pipeline:

  # Calibrate detector
  - reader.YAMLReader:
      filename: edd_config/ceria_calibration_config.yaml
      schema: MCACeriaCalibrationConfig
  - processor.MCACeriaCalibrationProcessor
  - writer.YAMLWriter:
      filename: edd_data/ceria_calibrated.yaml
      force_overwrite: true

  # Gather calibrated detector data
  - reader.MultipleReader:
      readers:
        - YAMLReader:
            filename: edd_config/map.yaml
            schema: MapConfig
        - YAMLReader:
            filename: edd_data/ceria_calibrated.yaml
            schema: MCACeriaCalibrationConfig
  - processor.MCADataProcessor
  - writer.NexusWriter:
      filename: edd_data/map_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - reader.MultipleReader:
      readers:
        - YAMLReader:
            filename: edd_data/map_detector_data.yaml
        - YAMLReader:
            filename: edd_config/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - processor.StrainAnalysisProcessor
  - writer.YAMLWriter:
      filename: edd_data/map_strain_data.yaml
      force_overwrite: true

