pipeline:

  # Combine tomography stacks
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: reconstructed.nex
        - common.YAMLReader:
            filename: combine.yaml
            schema: TomoCombineConfig
  - tomo.TomoDataProcessor:
      output_folder: tomo_combine_plots
      save_figs: 'only'
  - common.NexusWriter:
      filename: output.nex
      force_overwrite: true
