pipeline:

  # Reduce tomography images
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: setup.nex
        - common.YAMLReader:
            filename: reduce.yaml
            schema: TomoReduceConfig
  - tomo.TomoDataProcessor:
      output_folder: tomo_reduce_plots
      save_figs: 'only'
  - common.NexusWriter:
      filename: output.nex
      force_overwrite: true
