pipeline:

  # Reconstruct tomography stacks
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: reduced.nex
        - common.YAMLReader:
            filename: reconstruct.yaml
            schema: TomoReconstructConfig
        - common.YAMLReader:
            filename: centers.yaml
            schema: TomoFindCenterConfig
  - tomo.TomoDataProcessor:
      output_folder: tomo_reconstruct_plots
      save_figs: 'only'
  - common.NexusWriter:
      filename: output.nex
      force_overwrite: true
