pipeline:

  # Download example data
  - common.URLReader:
      url: https://gitlab01.classe.cornell.edu/api/v4/projects/308/repository/files/saxswaxs%2fdata.tar/raw?ref=main
      headers:
        PRIVATE-TOKEN: # your token here
  - common.URLResponseProcessor
  - common.ExtractArchiveWriter:
      filename: examples/saxswaxs

  # Collect map data
  - common.YAMLReader:
      filename: examples/saxswaxs/map_1d.yaml
      schema: MapConfig
  - common.MapProcessor
  - common.NexusWriter:
      filename: examples/saxswaxs/saxswaxs_map.nxs
      force_overwrite: true

  # Integrate map detetcor data
  - common.MultipleReader:
      readers:
        - YAMLReader:
            filename: examples/saxswaxs/map_1d.yaml
            schema: MapConfig
        - YAMLReader:
            filename: examples/saxswaxs/integration_saxs_azimuthal.yaml
            schema: IntegrationConfig
  - common.IntegrateMapProcessor
  - common.NexusWriter:
      filename: examples/saxswaxs/saxs_azimuthal_integrated.nxs
      force_overwrite: true
