name: chap_test_20230411
owner: ximgchess
description: A generic test pipeline for CHAP
remote_repository_url: https://github.com/CHESSComputing/ChessAnalysisPipeline
type: unrestricted
categories:
- Structural Materials Analysis
