<<<<<<< HEAD
name: chap_test_20230328
owner: kls286
description: A generic test pipeline for CHAP
remote_repository_url: https://github.com/CHESSComputing/ChessAnalysisPipeline/tree/galaxy
=======
name: chap_test_20230411
owner: ximgchess
description: A generic test pipeline for CHAP
remote_repository_url: https://github.com/CHESSComputing/ChessAnalysisPipeline
>>>>>>> galaxy
type: unrestricted
categories:
- Structural Materials Analysis
