pipeline:

  # Download example data
  - common.URLReader:
      url: https://gitlab01.classe.cornell.edu/api/v4/projects/308/repository/files/edd%2fdata.tar/raw?ref=main
      headers:
        PRIVATE-TOKEN: # your token here
  - common.URLResponseProcessor
  - common.ExtractArchiveWriter:
      filename: examples/edd

  # Calibrate detector
  - common.YAMLReader:
      filename: examples/edd/ceria_calibration_config.yaml
      schema: MCACeriaCalibrationConfig
  - edd.MCACeriaCalibrationProcessor
  - common.YAMLWriter:
      filename: examples/edd/ceria_calibrated.yaml
      force_overwrite: true

  # Gather calibrated detector data
  - common.MultipleReader:
      readers:
        - YAMLReader:
            filename: examples/edd/map.yaml
            schema: MapConfig
        - YAMLReader:
            filename: examples/edd/ceria_calibrated.yaml
            schema: MCACeriaCalibrationConfig
  - edd.MCADataProcessor
  - common.NexusWriter:
      filename: examples/edd/map_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - common.MultipleReader:
      readers:
        - NexusReader:
            filename: examples/edd/map_detector_data.nxs
        - YAMLReader:
            filename: examples/edd/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - common.StrainAnalysisProcessor
  - common.YAMLWriter:
      filename: examples/edd/map_strain_data.yaml
      force_overwrite: true

