config:
  root: examples/edd
  outputdir: output
  interactive: false
  log_level: DEBUG
  profile: false

energy:

  # Read the detector data
  - common.SpecReader:
      config:
        station: id1a3
        experiment_type: EDD
        spec_scans:
          - spec_file: ceria_2222-2/spec.log
            scan_numbers: 1

  # Perform energy calibration
  - edd.MCAEnergyCalibrationProcessor:
      config:
        background: constant
        baseline: true
        mask_ranges: [[420, 600]]
        max_peak_index: 0
        max_energy_kev: 150.0
        peak_energies: [34.717, 39.255, 40.231]
        detectors:
          - id: mca1
      save_figures: true
      schema: edd.models.MCAEnergyCalibrationConfig

  # Save the calibration configuration at the only-energy-calibrated stage
  - common.YAMLWriter:
      filename: energy_calibration_result.yaml
      force_overwrite: true
      schema: edd.models.MCAEnergyCalibrationConfig

tth:

  # Read the tth calibration spec configuration and the 
  # calibration configuration at the only-energy-calibrated stage
  - pipeline.MultiplePipelineItem:
      items:
        - common.SpecReader:
            config:
              station: id1a3
              experiment_type: EDD
              spec_scans:
                - spec_file: ceria_2222-2/spec.log
                  scan_numbers: 1
        - common.YAMLReader:
            filename: output/energy_calibration_result.yaml
            schema: edd.models.MCAEnergyCalibrationConfig

  # Perform the tth calibration
  - edd.MCATthCalibrationProcessor:
      config:
        energy_mask_ranges: [[51.9, 96.9], [103.1, 107.8]]
        tth_initial_guess: 7.85
      save_figures: true

  # Save the energy-and-tth-calibrated calibration configuration
  - common.YAMLWriter:
      filename: tth_calibration_result.yaml
      force_overwrite: true

map:

  # Get the map configuration
  - edd.EddMapReader:
      parfile: set2_c1-1/id1a3-wbmapscan-set2_c1-1.par
      scan_numbers: '1-13, 21-30, 32-34, 42-54'
      dataset_id: 1
      schema: common.models.map.MapConfig
  - common.YAMLWriter:
      filename: map_config.yaml
      force_overwrite: true
      schema: common.models.map.MapConfig
  - common.MapProcessor:
      num_proc: 1
      detectors:
        - id: mca1
  - common.NexusWriter:
      filename: raw_data.nxs
      force_overwrite: true

strain:

  # Get microstrain maps
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: output/raw_data.nxs
        - common.YAMLReader:
            filename: output/tth_calibration_result.yaml
            schema: edd.models.MCATthCalibrationConfig
  - edd.StrainAnalysisProcessor:
      config:
        detectors:
          - id: mca1
            background: constant
            baseline: true
            rel_height_cutoff: 0.02
            energy_mask_ranges: [[55., 123.]]
        find_peaks: true
        materials:
          - material_name: steel_set
            sgnum: 229
            lattice_parameters: 2.86825
        skip_animation: false
      save_figures: true
  - common.NexusWriter:
      filename: strain_map.nxs
      force_overwrite: true
