pipeline:

  # Download example data
  - common.URLReader:
      url: https://gitlab01.classe.cornell.edu/api/v4/projects/308/repository/files/edd%2fdata.tar/raw?ref=main
      headers:
        PRIVATE-TOKEN: # your token here
  - common.ExtractArchiveWriter:
      filename: examples/edd

  # Calibrate detector
  - common.YAMLReader:
      filename: examples/edd/ceria_calibration_config.yaml
      schema: edd.models.MCACeriaCalibrationConfig
  - edd.MCACeriaCalibrationProcessor
  - common.YAMLWriter:
      filename: examples/edd/ceria_calibrated.yaml
      force_overwrite: true

  # Measure diffraction volume length
  - common.YAMLReader:
      filename: examples/edd/dvl_measurement.yaml
      schema: edd.models.DiffractionVolumeLengthConfig
  - edd.DiffractionVolumeLengthProcessor:
      dvl_model: manual
  - common.YAMLWriter:
      filename: examples/edd/dvl_measured.yaml
      force_overwrite: true

  # Gather calibrated detector data
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: examples/edd/map.yaml
            schema: common.models.map.MapConfig
        - common.YAMLReader:
            filename: examples/edd/ceria_calibrated.yaml
            schema: edd.models.MCACeriaCalibrationConfig
  - edd.MCADataProcessor
  - common.NexusWriter:
      filename: examples/edd/map_detector_data.nxs
      force_overwrite: true

  # Compute sample strain map
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: examples/edd/map_detector_data.nxs
        - common.YAMLReader:
            filename: examples/edd/strain_analysis_config.yaml
            schema: StrainAnalysisConfig
  - common.StrainAnalysisProcessor
  - common.YAMLWriter:
      filename: examples/edd/map_strain_data.yaml
      force_overwrite: true

