pipeline:
  - common.BinaryFileReader:
      filename: examples/inference/img4.png
  - inference.TFaaSImageProcessor:
      url: "http://localhost:8083"
      model: mnist
      verbose: true
  - writer.Writer:
      filename: examples/inference/predictions.json
