pipeline:

  # Collect map data
  - reader.YAMLReader:
      filename: saxswaxs_config/map_1d.yaml
  - processor.MapProcessor
  - writer.NexusWriter:
      filename: saxswaxs_data/saxswaxs_map.nxs
      force_overwrite: true

  # Integrate map detetcor data
  - reader.MultipleReader:
      readers:
        map_config:
          NexusReader:
            filename: saxswaxs_data/saxswaxs_map.nxs
        integration_config:
          YAMLReader:
            filename: saxswaxs_config/integration_saxs_azimuthal.yaml
  - processor.IntegrationProcessor
  - writer.NexusWriter:
      filename: saxswaxs_data/saxs_azimuthal_integrated.nxs
      force_overwrite: true
