name: galaxy-tools

on:
  push:
    tags:
      - v*.*.*

jobs:
  update-toolshed-repo:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install planemo
      run: |
        python -m pip install --upgrade pip
        pip install planemo
    - name: Update tool version macro with CHAP version (tag) name
      run: |
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" galaxy-tools/macros.xml
    - name: Update toolshed
      run: |
        planemo shed_update --shed_target testtoolshed --shed_key ${{secrets.XIMGCHESS_TESTTOOLSHED_KEY}}$ galaxy-tools
