name: unittests

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Run ${{ matrix.env-name }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false 
      matrix:
        python-version: ["3.11", "3.14.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
        activate-environment: ""

    - name: Install Conda-only package
      run: |
        conda install -y -c hexrd hexrd

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r CHAP/test/requirements-${{ matrix.python-version }}.txt
        sed -i "s/PACKAGE_VERSION/0.0.0/" setup.py
        sed -i "s/PACKAGE_VERSION/0.0.0/" CHAP/__init__.py
        pip install -e .

    - name: Run CHAP unittests
      run: python -m unittest CHAP.test

    - name: Run CHAP pytests
      run: pytest CHAP/test/ --ignore=CHAP/test/saxswaxs/server/
