pipeline:

  # Create a simulated stack of tomography images
  - common.YAMLReader:
      filename: examples/tomo/tomo_sim_id3b.yaml
      schema: TomoSimConfig
  - tomo.TomoSimFieldProcessor
  - common.NexusWriter:
      filename: examples/tomo/hollow_cube_SIM_003.h5
      force_overwrite: true

  # Create the dark field for the simulation
  - common.NexusReader:
      filename: examples/tomo/hollow_cube_SIM_003.h5
      schema: TomoSimField
  - tomo.TomoDarkFieldProcessor
  - common.NexusWriter:
      filename: examples/tomo/hollow_cube_SIM_001.h5
      force_overwrite: true

  # Create the bright field for the simulation
  - common.NexusReader:
      filename: examples/tomo/hollow_cube_SIM_003.h5
      schema: TomoSimField
  - tomo.TomoBrightFieldProcessor:
      num_image: 10
  - common.NexusWriter:
      filename: examples/tomo/hollow_cube_SIM_002.h5
      force_overwrite: true

  # Create the SPEC file for the simulation
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: examples/tomo/hollow_cube_SIM_001.h5
            schema: TomoDarkField
        - common.NexusReader:
            filename: examples/tomo/hollow_cube_SIM_002.h5
            schema: TomoBrightField
        - common.NexusReader:
            filename: examples/tomo/hollow_cube_SIM_003.h5
            schema: TomoSimField
  - tomo.TomoSpecProcessor:
      scan_numbers: [1, 2, 3]
  - common.TXTWriter:
      filename: examples/tomo/hollow_cube
      force_overwrite: true

  # Full tomography reconstruction
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: examples/tomo/map_id3b.yaml
            schema: MapConfig
        - common.YAMLReader:
            filename: examples/tomo/reduce_data_id3b.yaml
            schema: TomoReduceConfig
        - common.YAMLReader:
            filename: examples/tomo/find_center_data_id3b.yaml
            schema: TomoFindCenterConfig
        - common.YAMLReader:
            filename: examples/tomo/reconstruct_data.yaml
            schema: TomoReconstructConfig
  - tomo.TomoDataProcessor:
      output_folder: examples/tomo/output
      save_figs: 'only'
  - common.NexusWriter:
      filename: examples/tomo/reconstruct_hollow_cube.nxs
      force_overwrite: true

