config:
  root: examples/tomo
  inputdir: config
  outputdir: hollow_cube
  interactive: true
  log_level: info
  profile: false

pipeline:

  # Convert the CHESS style map
  - common.ConfigReader:
      filename: map_id3b.yaml
      schema: common.models.map.MapConfig
  - common.MapProcessor:
      num_proc: 1
      detectors:
        - id: sim
      schema: tomofields
  - common.SpecReader:
      config:
        station: id3b
        experiment_type: TOMO
        spec_scans:
        - spec_file: ../data/hollow_cube/hollow_cube
          scan_numbers:
          - 1
      detectors:
        - id: sim
      schema: darkfield
  - common.SpecReader:
      inputdir: ../data/hollow_cube
      config:
        station: id3b
        experiment_type: TOMO
        spec_scans:
        - spec_file: hollow_cube
          scan_numbers:
          - 2
      detectors:
        - id: sim
      schema: brightfield
  - common.ConfigReader:
      filename: detector.yaml
      schema: tomo.models.Detector
  - tomo.TomoCHESSMapConverter
 
  # Full tomography reconstruction
  - common.ConfigReader:
      filename: reduce_data_id3b.yaml
      schema: tomo.models.TomoReduceConfig
  - common.ConfigReader:
      filename: find_center_id3b.yaml
      schema: tomo.models.TomoFindCenterConfig
  - common.ConfigReader:
      filename: reconstruct_data.yaml
      schema: tomo.models.TomoReconstructConfig
  - tomo.TomoDataProcessor:
      outputdir: saved_figs
      save_figs: 'only'
  - common.NexusWriter:
      filename: reconstructed_data.nxs
      force_overwrite: true
