config:
  root: examples/tomo
  inputdir: config
  outputdir: hollow_pyramid
  interactive: true
  log_level: INFO
  profile: false

pipeline:

  # Convert the CHESS style map
  - common.YAMLReader:
      filename: map_id3a_pyramid.yaml
      schema: common.models.map.MapConfig
  - common.MapProcessor:
#      config:
#        title: hollow_pyramid
#        station: id3a
#        experiment_type: TOMO
#        sample:
#          name: hollow_pyramid
#        spec_scans:
#        - spec_file: ../data/hollow_pyramid/spec.log
#          scan_numbers: [3, 4, 5]
#        independent_dimensions:
#        - label: rotation_angles
#          units: degrees
#          data_type: scan_column
#          name: theta
#        - label: x_translation
#          units: mm
#          data_type: smb_par
#          name: ramsx
#        - label: z_translation
#          units: mm
#          data_type: smb_par
#          name: ramsz
      num_proc: 1
      detectors:
        - id: sim
      schema: tomofields
#  - common.NexusWriter:
#      filename: map_hollow_pyramid.nxs
#      force_overwrite: true
  - pipeline.MultiplePipelineItem:
      items:
#        - common.NexusReader:
#            filename: ../hollow_pyramid/map_hollow_pyramid.nxs
#            schema: tomofields
        - common.SpecReader:
            config:
              station: id3a
              experiment_type: TOMO
              spec_scans:
              - spec_file: ../data/hollow_pyramid/spec.log
                scan_numbers:
                - 1
            detectors:
              - id: sim
            schema: darkfield
        - common.SpecReader:
            inputdir: ../data/hollow_pyramid
            config:
              station: id3a
              experiment_type: TOMO
              spec_scans:
              - spec_file: spec.log
                scan_numbers:
                - 2
            detectors:
              - id: sim
            schema: brightfield
        - common.YAMLReader:
            filename: detector_pyramid.yaml
            schema: tomo.models.Detector
  - tomo.TomoCHESSMapConverter
#  - common.NexusWriter:
#      filename: chess_map_hollow_pyramid.nxs
#      force_overwrite: true

  # Full tomography reconstruction
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: find_center_id3a.yaml
            schema: tomo.models.TomoFindCenterConfig
        - common.YAMLReader:
            filename: reconstruct_data.yaml
            schema: tomo.models.TomoReconstructConfig
        - common.YAMLReader:
            filename: combine_data_id3a.yaml
            schema: tomo.models.TomoCombineConfig
  - tomo.TomoDataProcessor:
      reduce_data: true
      outputdir: saved_figs
      save_figs: 'only'
  - common.NexusWriter:
      filename: combined_hollow_pyramid.nxs
      force_overwrite: true

