config:
  root: examples/tomo/hollow_cube

pipeline:

  # Create a simulated stack of tomography images
  - common.YAMLReader:
      filename: ../tomo_sim_id3b.yaml
      schema: tomo.models.TomoSimConfig
  - tomo.TomoSimFieldProcessor
  - common.NexusWriter:
      filename: hollow_cube_SIM_003.h5
      force_overwrite: true

  # Create the dark field for the simulation
  - common.NexusReader:
      filename: hollow_cube_SIM_003.h5
      schema: tomo.models.TomoSimField
  - tomo.TomoDarkFieldProcessor
  - common.NexusWriter:
      filename: hollow_cube_SIM_001.h5
      force_overwrite: true

  # Create the bright field for the simulation
  - common.NexusReader:
      filename: hollow_cube_SIM_003.h5
      schema: tomo.models.TomoSimField
  - tomo.TomoBrightFieldProcessor:
      num_image: 10
  - common.NexusWriter:
      filename: hollow_cube_SIM_002.h5
      force_overwrite: true

  # Create the SPEC file for the simulation
  - pipeline.MultiplePipelineItem:
      items:
        - common.NexusReader:
            filename: hollow_cube_SIM_001.h5
            schema: tomo.models.TomoDarkField
        - common.NexusReader:
            filename: hollow_cube_SIM_002.h5
            schema: tomo.models.TomoBrightField
        - common.NexusReader:
            filename: hollow_cube_SIM_003.h5
            schema: tomo.models.TomoSimField
  - tomo.TomoSpecProcessor:
      scan_numbers: [1, 2, 3]
  - common.TXTWriter:
      filename: hollow_cube
      force_overwrite: true

  # Full tomography reconstruction
  - pipeline.MultiplePipelineItem:
      items:
        - common.YAMLReader:
            filename: ../map_id3b.yaml
            schema: common.models.map.MapConfig
        - common.YAMLReader:
            filename: ../reduce_data_id3b.yaml
            schema: tomo.models.TomoReduceConfig
        - common.YAMLReader:
            filename: ../find_center_data_id3b.yaml
            schema: tomo.models.TomoFindCenterConfig
        - common.YAMLReader:
            filename: ../reconstruct_data.yaml
            schema: tomo.models.TomoReconstructConfig
  - tomo.TomoDataProcessor:
      output_folder: examples/tomo/hollow_cube/output
      save_figs: 'only'
  - common.NexusWriter:
      filename: reconstruct_hollow_cube.nxs
      force_overwrite: true

